# ===== LOCAL MYSQL CONFIG =====
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate dialect for MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect